// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
export interface StoryblokFeature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokGrid {
  columns?: (StoryblokFeature | StoryblokGrid | StoryblokPage | StoryblokTeaser | StoryblokTest)[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokPage {
  body?: (StoryblokFeature | StoryblokGrid | StoryblokPage | StoryblokTeaser | StoryblokTest)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokTeaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokTest {
  component: "test";
  _uid: string;
  [k: string]: unknown;
}
