// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset, StoryblokRichtext } from '../storyblok.d.ts';
export interface StoryblokFeature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokGrid {
  columns?: (
    | StoryblokFeature
    | StoryblokGrid
    | StoryblokImage
    | StoryblokPage
    | StoryblokSeoFields
    | StoryblokTeaser
    | StoryblokTest
    | StoryblokTextBlock
  )[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokImage {
  image: StoryblokAsset;
  component: "image";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokPage {
  body?: (
    | StoryblokFeature
    | StoryblokGrid
    | StoryblokImage
    | StoryblokPage
    | StoryblokSeoFields
    | StoryblokTeaser
    | StoryblokTest
    | StoryblokTextBlock
  )[];
  seo_fields: StoryblokSeoFields[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokSeoFields {
  title?: string;
  description?: string;
  og_image?: StoryblokAsset;
  no_index?: boolean;
  component: "seo_fields";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokTeaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokTest {
  component: "test";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokTextBlock {
  text?: StoryblokRichtext;
  links?: (
    | StoryblokFeature
    | StoryblokGrid
    | StoryblokImage
    | StoryblokPage
    | StoryblokSeoFields
    | StoryblokTeaser
    | StoryblokTest
    | StoryblokTextBlock
  )[];
  component: "text_block";
  _uid: string;
  [k: string]: unknown;
}
